### ISSUE TITLE
Each branch name should have it's purpose

### ISSUE THREAD

**Issue by kwon-evan** [minocrafft/keepit#3]
이름으로 나누는 것이 아니라, 명확한 목적이나 개발목표를 가진 브랜치가 되어야할 것 같아요

**Comment by minocrafft** [comment]
애초에 지금 브랜치 만들어진 이유가 각자 작업물을 만들어보는거에 의의를 둔거라 추후에 하나로 결정되면 기능별로 브랜치 만들어서 작업하면 좋을 거 같습니다~
