### ISSUE TITLE
AWS 서비스 파이프라인

### ISSUE THREAD

**Issue by kwon-evan** [minocrafft/keepit#5]
fastapi 올려서 서비스 할 수 있도록

**Comment by minocrafft** [comment]
EC2로 다시 만들어오기

**Comment by NahyeonKang** [comment]
1. chmod 400 dev-key.pem
2. ssh -i dev-key.pem ubunto@3.39.25.46
3. fastapi 파일 업로드
4. 필요한 패키지 설치 후 실행

AWS console 보안 그룹에서 포트번호 등록 필요

**Comment by NahyeonKang** [comment]
터미널 종료 시에도 백그라운드에서 계속 실행
-> nohup
터미널이 종료되거나 네트워크 연결이 끊어져도 백그라운드에서 프로세스를 계속 실행하게 하는 명령어.

sudo apt install nohup
nohup uvicorn main:app —reload

-> tmux라는 것도 있음. 좀 복잡
